
#spring:  datasource:     url: jdbc:h2:mem:DB_PATIENTS
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/DB_Patients
    username: root
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto:
    properties:
      hibernate:
         dialect: org.hibernate.dialect.MySQL5Dialect




